Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
Traceback (most recent call last):
      File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))
    
During handling of the above exception, another exception occurred:

tree = pytree_utils.ParseCodeToTree(unformatted_source)
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
        return self.parse_tokens(tokens, debug)ast.parse(code)

  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    return compile(source, filename, mode, flags,
  File "<unknown>", line 77
    fc_layer='dict(type='fc_layer')'),
                         ^
SyntaxError: invalid syntax    
raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    tree = parser_driver.parse_string(code, debug=False)    return compile(source, filename, mode, flags,

  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
  File "<unknown>", line 77
    fc_layer='dict(type='fc_layer')'),
                         ^
SyntaxError: invalid syntax
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 77
    fc_layer='dict(type='fc_layer')'),
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
      File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):f.write(self.pretty_text)
    
if p.addtoken(type, value, (prefix, start)):  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text

  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
        raise ParseError("bad input", type, value, context)raise ParseError("bad input", type, value, context)

lib2to3.pgen2.parselib2to3.pgen2.parse..ParseErrorParseError: : bad input: type=1, value='fc_layer', context=('', (77, 33))bad input: type=1, value='fc_layer', context=('', (77, 33))

    
During handling of the above exception, another exception occurred:

text, _ = FormatCode(text, style_config=yapf_style, verify=True)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
      File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    raise ParseError("bad input", type, value, context)
    lib2to3.pgen2.parsereturn compile(source, filename, mode, flags,.
ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

  File "<unknown>", line 77
Traceback (most recent call last):
      File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
fc_layer='dict(type='fc_layer')'),
                   main() 
    File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
       ^
SyntaxError: invalid syntax
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
      File "<unknown>", line 77
return compile(source, filename, mode, flags,    
fc_layer='dict(type='fc_layer')'),
       File "<unknown>", line 77
       fc_layer='dict(type='fc_layer')'),
                               ^
 SyntaxError :  invalid syntax 
       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 77
    fc_layer='dict(type='fc_layer')'),
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='fc_layer', context=('', (77, 33))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 204, in <module>
    main()
  File "/home/thaddaus/MasterthesisCode/./mmdetection/tools/train_adaptive.py", line 135, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 461, in dump
    f.write(self.pretty_text)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/utils/config.py", line 416, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 77
    fc_layer='dict(type='fc_layer')'),
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/thaddaus/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/thaddaus/anaconda3/envs/open-mmlab/bin/python', '-u', './mmdetection/tools/train_adaptive.py', '--local_rank=7', 'mmdetection/configs/adaptive/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person_adaptive.py', '--launcher', 'pytorch', '--work-dir', '/home/thaddaus/WORK_DIRS/GPA/tuning/coco_piropo_100a_TwoStageDetectorAdaptiveAutoBalance_10_01_100_01_mean_squared_dicttypefclayernFalsegTrue_seed', '--seed', '42', '--cfg-options', 'data.samples_per_gpu=2', 'data.train_src.ann_file=/data/COCO/annotations/person_train2017.json', 'data.train_src.img_prefix=/data/COCO/train2017', 'data.train_tgt.ann_file=/data/PIROPO/omni_training_100a.json', 'data.train_tgt.img_prefix=None', 'data.val.ann_file=/data/PIROPO/omni_test2.json', 'data.val.img_prefix=None', 'runner.max_epochs=40', 'lr_config.step=[200]', 'evaluation.interval=1', 'checkpoint_config.interval=200', 'model.type=TwoStageDetectorAdaptiveAutoBalance', 'model.train_cfg.gpa.loss_roi_intra=10', 'model.train_cfg.gpa.loss_roi_inter=0.1', 'model.train_cfg.gpa.loss_rcnn_intra=100', 'model.train_cfg.gpa.loss_rcnn_inter=0.1', 'model.train_cfg.gpa.distance=mean_squared', 'model.train_cfg.gpa.normalize=False', 'model.train_cfg.gpa.use_graph=True', "model.train_cfg.gpa.fc_layer=dict(type='fc_layer')"]' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Killing subprocess 56744
Killing subprocess 56745
Killing subprocess 56746
Killing subprocess 56747
Killing subprocess 56748
Killing subprocess 56749
Killing subprocess 56750
Killing subprocess 56751
